### ISSUE TITLE
Convert a json object into json string

### ISSUE THREAD

**Issue by yashcfg** [sheredom/json.h#100]
I am not sure if it goes out of scope for this library but I have a use case where I want to parse an object and return value (object type) of a key.

eg. - 

if json string is - `"{\"a\":11,\"b\":{\"c\":22,\"d\":\"1234\"}}"`

then I want to return `"{\"c\":22,\"d\":\"1234\"}"`

Let me know if it is possible. Thanks

**Comment by sheredom** [comment]
It is possible yup.

**Comment by yashcfg** [comment]
@sheredom can you share example code?
