### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [sheredom/json.h#2]
I would like to point out that an identifier like "[`__JSON_H__`](https://github.com/sheredom/json.h/blob/c393d6ba4fe7233e874292806f90909402fdf812/json.h#L26)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by sheredom** [comment]
Just accepted a pull request to fix that issue. I've spent too much time as a compiler dev it seems to forget trivial things like this ;)
