### ISSUE TITLE
This causes the parser to hang

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [sheredom/json.h#26]
const char* str = R"fs(
		"groovy": "yep"
		asdf: 42
	)fs";
	
	printf( "Preparing to parse\n" );
	json_value_s* value = json_parse_ex(str, strlen(str), json_parse_flags_allow_simplified_json, 0);	
	printf( "Never get's here...\n" );

	return 0;

**Comment by sheredom** [comment]
Thanks for this! The MR https://github.com/sheredom/json.h/pull/27 is currently testing my fix for this. Hope this works for you!

**Comment by TimothyWrightSoftware** [comment]
Yes, that worked.  Thank you!
