### ISSUE TITLE
Line information in DOM

### ISSUE THREAD

**Issue by alexshafranov** [sheredom/json.h#38]
First of all, thanks for the great library!

I use some kind of schema to interpret the parsed DOM.
As this can fail, it would be nice to have line numbers to report to a user.

Looking at the code it seems it could be a matter of copying line number from the parsing state to `json_value_s` struct.

Do you mind increased `json_value_s` size?

**Comment by sheredom** [comment]
First off - thanks for using my library!

How much extra data were you wanting to track? If it was one size_t offset into the stream, that wouldn't be so bad, but if its 3 size_t's (offset in stream, line number, offset in line number) there is quite a bit more data and I'd want to have a think about that :smile:

**Comment by alexshafranov** [comment]
For my specific use case it would be just fine to have a single `size_t` for a line number.

Though I agree that the more generic approach would be to store an offset to stream instead.
In that case the library can also provide some kind of look-aside table translating offsets to locations.

**Comment by sheredom** [comment]
Ok, if you propose a pull request with that in it I'll accept it :smile:
