### ISSUE TITLE
json.h parser allocates memory it doesn't use

### ISSUE THREAD

**Issue by fireice-uk** [sheredom/json.h#43]
Hello,

The parser seems to overestimate the amount of memory needed for the DOM. On a x64 build it will be exactly 32 bytes per every JSON object's key pair. It seems to be happening because both json_get_object_size and the helper functions json_get_key_size and json_get_value_size add to the dom_size. Not sure which addition (in the functions, or at the end of json_get_object_size) is the correct one.

Example input '{"a":"b"}', no parser flags.
Calculated dom_size = 136
data_size = 4
total_size = 140
Actual DOM end is at offset 104, memory between 104 and 136 is not written to.

**Comment by fireice-uk** [comment]
Just double checked and the issue is in a x86 build too with 16 bytes wasted.

**Comment by sheredom** [comment]
@fireice-uk is this the bug you just fixed in #45 ?

**Comment by fireice-uk** [comment]
Correct, together with some bugs that were masked by it. I will close this issue.
