### ISSUE TITLE
Wrong parsing error code for premature end of buffer

### ISSUE THREAD

**Issue by ederlf** [sheredom/json.h#47]
If i try to parse something like this:

    {
         "dps":[1, 2, 3
    }

the error code returned is **json_parse_error_expected_comma** 
Would not be expected to have **json_parse_error_premature_end_of_buffer** ?

**Comment by sheredom** [comment]
Yeah that is wrong for sure - it should have said comma or ] for the end of the array. I'll add a test case thanks!
