### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by ocornut** [sheredom/json.h#5]
I started using this and I'll be wanting some more error reporting (being able to report line number/row and possibly type of errors). I think I can add them to the code but I was wondering what your priorities were in term of speed/functionalities trade-off and if they were good candidate for a merge.

For now I have just added line_no and line_start_offset to the json_parse_state_s structure which are only altered when encountering a \n. Byte count from beginning of line can be calculated using (offset-line_start_offset), it isn't a character count per se but already useful and the program can possibly output clang-style error reporting in context from that.

Since this is C my idea was to add an extra entry point, json_parse_ex() taking something like a `json_parse_result_s*` to output information such as the type of error and line number. Would you want such patch?

**Comment by sheredom** [comment]
First off - I'd happily accept that merge Omar :)

I think your idea of having separate entry points that have the error checking seems like the best approach. To be fair though - if the overhead for error checking was within 10% I'd not be against just having that as the main entry point.

**Comment by ocornut** [comment]
To clarify, 
- The different entry point are just because of the lack of default parameter and to avoid breaking the API, but since the library is recent I would personally prefer to add a third parameter and allow it to be NULL, since the breakage would be minor and obvious to fix.
- The overhead will be regardless of checking errors or not. It's likely to be way under 10%.

**Comment by sheredom** [comment]
Yup, totally happy for you to modify the entry points then!

**Comment by ocornut** [comment]
How about allowing trailing commas at the end of an object,array list ?

**Comment by sheredom** [comment]
So technically its malformed JSON to do that, but in practice I wonder if the usability aspect is more important than directly conforming to the spec? I'll accept that as part of a patch for sure, and just document the variance from JSON. :)

**Comment by ocornut** [comment]
The patch is simpler but probably trickier if we want to allow both forms (and report as malformed).
Since this library is about practicalities I assume it is something desirable. The lack of this in the specs is very annoying to anyone hand-editing JSON files.

**Comment by sheredom** [comment]
Just allow the trailing commas in whatever you submit as a patch, I agree its annoying!

**Comment by ocornut** [comment]
Curious why "size_t type;" in json_value_s is a size_t (untyped and up to 8 bytes) instead of an enum or probably a smaller type?

**Comment by sheredom** [comment]
Heh, that is simply because I compile with all warnings on, and warnings as errors, with MSVC, and if that isn't the same size as a pointer, the struct has padding added and I get an error >.<

**Comment by sheredom** [comment]
Ok this in done and in (yay - thanks!) I'll close this issue now.
