### ISSUE TITLE
ESP8266 Arduino

### ISSUE THREAD

**Issue by denden4444** [sheredom/json.h#62]
Wow this looks awesome :-)

Is there any way of getting this to work on an ESP8266/NodeMCU ?

I would like to serialize a struct and then do the reverse if possible.

Would be happy to try and feedback results.

Kind regards
Den

**Comment by sheredom** [comment]
Hey Den,

I mean its just a C library - so it should work anywhere that has a C compiler. I have zero experience with either of those things you mentioned, you'll have to investigate yourself!

If you do get it working, I'd love to hear about your experience.

Cheers,
-Neil.
